name: "deploy"

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Build image
              run: |
                  docker image build --tag app/grs:${{ github.sha }} .

            - name: Dokku
              uses: dokku/github-action@master
              env:
                  ssh_host_key: ${{ secrets.SSH_HOST_KEY }}
                  ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
                  branch: master
                  git_remote_url: ssh://dokku@165.232.65.116:22/grs
                  deploy_docker_image: app/grs:${{ github.sha }}
                  trace: "1"
                  git_push_flags: "-vvv"
