name: "deploy"

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Build image
              run: |
                  docker image build --tag app/grs:${{ github.sha }} .

            - name: Dokku
              uses: dokku/github-action@v1.4.0
              env:
                  ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
                  branch: master
                  git_remote_url: ssh://dokku@${{ secrets.SERVER_IP }}:22/grs
                  deploy_docker_image: app/grs:${{ github.sha }}
